import json
from typing import Dict, List

import httpx
from groq import Groq

from app.config import settings

SYSTEM_PROMPT = """You are an expert AI Accounting Assistant. Your job is to help users resolve invoice validation errors (like math mismatches).
You will be provided with the extracted JSON data of an invoice and a list of validation issues generated by the system.

Your goal is to provide a concise, actionable, and specific step-by-step resolution suggestion for the user. 
WARNING: Do not attempt to calculate the exact corrected math values yourself, as AI models frequently make arithmetic errors. 
Instead, identify which fields are conflicting and suggest the user review them. For example, "It appears the tax amount does not align with the subtotal and total. Please review and correct the tax amount."

Do not write a long essay. Provide a short, direct, and helpful suggestion (1-3 sentences max).
Do not use markdown like * or #, just return plain text.
"""

def generate_resolution_suggestion(extracted: Dict, issues: List[str]) -> str | None:
    """
    Calls the Groq LLM to generate a helpful resolution suggestion based on the 
    extracted data and the validation issues.
    """
    if not issues:
        return None

    if not settings.groq_api_key:
        return "Configure your Groq API key to enable AI Resolution Suggestions."

    try:
        http_client = httpx.Client(timeout=30.0, follow_redirects=True)
        client = Groq(api_key=settings.groq_api_key, http_client=http_client)

        user_content = f"EXTRACTED INVOICE DATA:\n{json.dumps(extracted, indent=2)}\n\nVALIDATION ISSUES:\n"
        for issue in issues:
            user_content += f"- {issue}\n"

        response = client.chat.completions.create(
            model=settings.groq_model,
            temperature=0,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_content},
            ],
        )

        suggestion = response.choices[0].message.content.strip()
        return suggestion
    except Exception as e:
        return f"AI Assistant could not generate a suggestion due to an error: {e}"
